{% set name = "aiozmq" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dac9069d36a47da439fa852ed37caaed3887b5928cb781e06a6a82e43682c6bb

build:
  noarch: python
  number: 1
  entry_points:
    - aiozmq-proxy = aiozmq.cli.proxy:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pyzmq !=17.1.2,>=13.1
  run_constrained:
    - msgpack >=0.5.0

test:
  imports:
    - aiozmq
    - aiozmq.cli
    - aiozmq.rpc
  commands:
    - aiozmq-proxy --help
  requires:
    - msgpack-python
    - python {{ python_min }}

about:
  home: http://aiozmq.readthedocs.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ZeroMQ integration with asyncio.
  doc_url: https://aiozmq.readthedocs.io/
  dev_url: https://github.com/aio-libs/aiozmq

extra:
  recipe-maintainers:
    - cjw85
    - beenje
