{% set name = "aiozmq" %}
{% set version = "0.9.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d7315bb77e2655fc3a5051ea22e79527d62c42e51b2420c4f6f3dcebae65230

build:
  noarch: python
  number: 0
  entry_points:
    - aiozmq-proxy = aiozmq.cli.proxy:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python >=3.4,<3.7
  run:
    - python >=3.4,<3.7
    - pyzmq >=13.1
  run_constrained:
    - msgpack >=0.4.0

test:
  imports:
    - aiozmq
    - aiozmq.cli
    - aiozmq.rpc
  commands:
    - aiozmq-proxy --help
  requires:
    - msgpack-python

about:
  home: http://aiozmq.readthedocs.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt 
  summary: ZeroMQ integration with asyncio.
  doc_url: https://aiozmq.readthedocs.io/
  dev_url: https://github.com/aio-libs/aiozmq

extra:
  recipe-maintainers:
    - cjw85
