travis:
  secure:
    BINSTAR_TOKEN: kRzH1KCiH9L5Y2u8KO2CsVQWsN1wGXE48mgjBjZGlD2NUFwBfo61bAJbv5WdU6Ylwb3TScOX4ZmXnVBAy5aYv7DqosbXzIuUQpkP2qfYpKfZeYlYNNj4Iiz2x9a603gFYG6/+N5/ZPcQoTs1AHL20rClfl8ERxab2Hv/i8yG7eDwBzDWSiG6T/HS9pThi2C3HtXG0fYAjMmCx6EbujneE24sMHEzB8pal6FpT41Dod9SGaFEzNTnM9dAXjhVWq9iuNU619VWkixzBFAVh06QDi0bUImJviaqrVjxmznlD8UzuXUSi+4UeMqkh2vTNG8f+/te1Hq+eO/Lx3kptzv8C+plIWgAqW2qM13NZEAgVrqVZIUmrO2FXsR+BzaSl/1F0uEBpauyH7IO3ZkLr2T6ttqdl+RmR1NbEGMLr/A0BdRwtNuGUqvjaia0dVkwczkjFw6wYy4ppdD5pzT4tlIQsniiJRTUgmx+k3UDU+C6XXbgske31aNhLt4Uuog3+2IiHCJQfgPn1toBWOs4ZeYdbR6C51RwkdLr+7v3gAEEagxmYK2G1W8eIxPPcShSllcmZG18wiTgToMl2Cm3g6jn+V6JBZbXyps1uCLeCG5+X/e4ao5mIo8mHLEQhLrj3syqNHVoBvnXrwcgbS8dB4e2IMmP43xLTVxt92af9PDz+lc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
